name: occupier
description: A Flutter project which helps you to know the number of customer in the shops, so that it can help you to manage your time.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pinput: ^3.0.1
  sms_autofill: ^2.3.0
  fluttertoast: ^8.2.2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.2
  country_picker: ^2.0.20
  firebase_storage: ^11.2.6
  modal_progress_hud_nsn: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/Google_logo.png
    - assets/images/Default_Profile_Photo.jpg
